# Generated by Django 2.2.12 on 2022-03-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220302_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
